/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface TestComponent {
    }
    interface Test2Component {
    }
}
declare global {
    interface HTMLTestComponentElement extends Components.TestComponent, HTMLStencilElement {
    }
    var HTMLTestComponentElement: {
        prototype: HTMLTestComponentElement;
        new (): HTMLTestComponentElement;
    };
    interface HTMLTest2ComponentElement extends Components.Test2Component, HTMLStencilElement {
    }
    var HTMLTest2ComponentElement: {
        prototype: HTMLTest2ComponentElement;
        new (): HTMLTest2ComponentElement;
    };
    interface HTMLElementTagNameMap {
        "test-component": HTMLTestComponentElement;
        "test2-component": HTMLTest2ComponentElement;
    }
}
declare namespace LocalJSX {
    interface TestComponent {
    }
    interface Test2Component {
    }
    interface IntrinsicElements {
        "test-component": TestComponent;
        "test2-component": Test2Component;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "test-component": LocalJSX.TestComponent & JSXBase.HTMLAttributes<HTMLTestComponentElement>;
            "test2-component": LocalJSX.Test2Component & JSXBase.HTMLAttributes<HTMLTest2ComponentElement>;
        }
    }
}
